version: "3"

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    ports:
      - "8001:8080"
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8002:8080"
    volumes:
      - ./dist:/dist
    environment:
      SWAGGER_JSON: /dist/service1/openapi.yml
      # URLS: '[{name: "service1", url: "/dist/service1/openapi.yml"}, {name: "service2", url: "/dist/service2/openapi.yml" }]'
  redocly-redoc:
    image: redocly/redoc
    depends_on:
      - swagger-script
    environment:
      PAGE_TITLE: redoc sample
      SPEC_URL: /service2/openapi.yml
    ports:
      - "8003:80"
    volumes:
      - ./dist/service2:/usr/share/nginx/html/service2
  swagger-script:
    image: node:18-alpine
    working_dir: /script
    volumes:
      - ./swagger-script:/script
      - script_node_modules:/script/node_modules
      - ./src:/src:cached
      - ./dist:/dist:cached
    command: sh -c "yarn && yarn watch"

volumes:
  script_node_modules:
