openapi: 3.1.0
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: ""
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
  - url: https://example.com/api/v1
    description: ""
tags:
  - name: hoge
    description: ""
paths:
  /hoge:
    get:
      tags:
        - hoge
      summary: hoge
      operationId: hoge
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/hoge"
